version: '3.5'
services:
    selenoid:
        image: "aerokube/selenoid:1.10.4" # update version if necessary
        ports:
            - "4444:4444"
        networks:
            - stargate
        volumes:
            - "$PWD/selenoid:/etc/selenoid" # remove '$PWD/' to run on Win here and below
            - "$PWD/selenoid/logs:/opt/selenoid/logs"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "$PWD/selenoid/video:/opt/selenoid/video/"
        environment:
            - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video/
        command: ["-conf", "/etc/selenoid/browsers.json", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid-network", "-limit", "10"]

    selenoid-ui:
        image: "aerokube/selenoid-ui:1.10.1"
        ports:
            - "8080:8080"
        links:
            - selenoid
        networks:
            - stargate
        command: ["--selenoid-uri", "http://selenoid:4444"]

    browsermob-proxy:
        image: "qautomatron/docker-browsermob-proxy:2.1.3"
        hostname: "bmp"
        ports:
            - "9090-9191:9090-9191"
        expose:
            - "9090-9099"
        networks:
            - stargate

networks:
    stargate:
        name: selenoid-network
        driver: bridge
        ipam:
            config:
                - subnet: 193.1.1.1/24
